### ISSUE TITLE
Improvements day 3

### ISSUE THREAD

**Issue by EmilGedda** [LukasSzerszen/AdventOfCode#12]
Consider using another plain old class called `ProblemInput` (or something better) and give it a fabric and a `ArrayList<Claim>` as members, instead of passing them around like loose pieces on a chess board. This will reduce the amount of code bloat in function signatures. I would then personally change `parseDay3Input` to a function named `parseInput` which returns a `ProblemInput` instead, keeping related data together. This way, `parseInput` can (should be able to) enforce read-only-ness of the fabric and the claims by making these members of `ProblemInput` final. This is preferable instead of having the developer litter the code with final everywhere the forced immutable variables goes, which reduces the signal-to-noise ratio and in turn readability. 

--

https://github.com/LukasSzerszen/AdventOfCode/blob/693926e439050bc6ee503a5bcc093e04d87138aa/src/Day3.java#L141

Ideally the constructor of `Claim` should be no more restrictive than the class itself. This means that taking a `Matcher` parameter from the Regex library is not optimal as `Claim` itself should not care about where the data came from.

--

These lines in `uniqueID`
https://github.com/LukasSzerszen/AdventOfCode/blob/693926e439050bc6ee503a5bcc093e04d87138aa/src/Day3.java#L51-L65
And function `populateMatrix` are identical.

--

https://github.com/LukasSzerszen/AdventOfCode/blob/693926e439050bc6ee503a5bcc093e04d87138aa/src/Day3.java#L136-L139
The consensus when using geometrical structures in code is to use the established nomenclature. As a claim is nothing other than a rectangle with an ID, these variables should really be named `x`, `y`, width, and `height` instead.

--

https://github.com/LukasSzerszen/AdventOfCode/blob/693926e439050bc6ee503a5bcc093e04d87138aa/src/Day3.java#L122-L132

Instead of running your regex for every single line in the input, why not run it on the full input once and aggregate the results? [See this link for reference on how to do this in Java 9](https://stackoverflow.com/a/46859130)

--

There are better solutions to part 2, and a more readable way to solve part 1.

Hints: 
Part 1: By separating the problem into filling the matrix and then counting the overlaps this could be solved in a more functional way using Streams.
Part 2: A `Matrix<HashSet<Integer>>` is not the best datastructure for this problem as it will contain a lot of redundant information. See if you can solve it using only `Matrix<Integer>`, and compare the differences in readability afterwards.

**Comment by LukasSzerszen** [comment]
Fixed; omitted class for keeping related data together, will keep in mind when implementing future solutions.
